Repository debionetwork/ui-components, pull requests merged in 2022-03, with the labels that each got.

#2 tests: component unit tests.
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/assets/alert-circle.png
  tests/unit/lib-components/avatar.spec.js
  tests/unit/lib-components/banner.spec.js
  tests/unit/lib-components/breadcrumbs.spec.js
  tests/unit/lib-components/button.spec.js
  tests/unit/lib-components/card.spec.js
  tests/unit/lib-components/dialog/alert-dialog.spec.js
  tests/unit/lib-components/dialog/dialog.spec.js
  tests/unit/lib-components/dialog/error-dialog.spec.js
  tests/unit/lib-components/dropdown.spec.js
  tests/unit/lib-components/file.spec.js
  tests/unit/lib-components/icon.spec.js
  tests/unit/lib-components/input.spec.js
  tests/unit/lib-components/modal.spec.js
  tests/unit/lib-components/rating.spec.js
  tests/unit/lib-components/recaptcha.spec.js
  tests/unit/lib-components/stepper.spec.js
  tests/unit/lib-components/textarea.spec.js
Labels: test

#3 docs: readme.
  README.md
Labels: documentation

#7 feat: git hooks
  .maintain/install-hooks.sh
  package.json
Labels: enhancement, test

#8 ci: github workflow tester
  .github/workflows/tester.yml
  package-lock.json
  package.json
Labels: test

#9 fix: fix image width on ui-debio-avatar
  src/components/UiDebioAvatar.vue
Labels: bug

#10 feat: package update v0.0.5
  package.json
Labels: enhancement
